services:
  - type: web
    name: ehealth-rbac
    runtime: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /login.php
    envVars:
      - key: BASE_URL
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: ehealth-rbac-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ehealth-rbac-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ehealth-rbac-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ehealth-rbac-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: ehealth-rbac-db
          property: password
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: E-Health RBAC
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        sync: false
      - key: UPLOAD_DIR
        value: /var/www/html/public/uploads/licenses/
      - key: UPLOAD_URL
        value: /uploads/licenses/

databases:
  - name: ehealth-rbac-db
    plan: starter
